language: node_js

script: 
  # Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
  # Use either `docker-compose` or individual `docker build` commands
  # Build docker image for api-feed
  - docker build -t udagram-api-feed ./udagram-api-feed
  # Build docker image for api-user
  - docker build -t udagram-api-user ./udagram-api-user
  # Build docker image for frontend
  - docker build -t udagram-frontend ./udagram-frontend
  # Build docker image for reverseproxy
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # Tagging for api-feed
  - docker tag udagram-api-feed maynoigi1997/udagram-api-feed:v1
  # Tagging for api-user
  - docker tag udagram-api-user maynoigi1997/udagram-api-user:v1
  # Tagging for api-frontend
  - docker tag udagram-frontend maynoigi1997/udagram-frontend:v1
  # Tagging for api-reverseproxy
  - docker tag udagram-reverseproxy maynoigi1997/udagram-reverseproxy
  # Push
  # Assuming dockerhub_password and dockerhub_username are set in the Travis repository settings
  # login to docker hub
  - echo "$dockerhub_password" | docker login -u "$dockerhub_username" --password-stdin
  # push udagram-api-feed
  - docker push maynoigi1997/udagram-api-feed:v1
  # push udagram-api-user
  - docker push maynoigi1997/udagram-api-user:v1
  # push udagram-frontend
  - docker push maynoigi1997/udagram-frontend:v1
  # push udagram-reverseproxy
  - docker push maynoigi1997/udagram-reverseproxy