apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reserseproxy
  template:
    metadata:
      labels:
        app: reserseproxy
    spec:
      containers:
      - name: reserseproxy
        image: letanhai1998/udagram-reverseproxy
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
